name: CiCD action
on:
  push:
    branches: [master]
jobs:
  testing:
    runs-on: ubuntu-latest
    env:
      PG_NAME: ${{secrets.PG_NAME}}
      PG_USER: ${{secrets.PG_USER}}
      PG_HOST: ${{secrets.PG_HOST}}
      PG_PASSWORD: ${{secrets.PG_PASSWORD}}
      PG_PORT: ${{secrets.PG_PORT}}

    steps:
      - name: проверка изменений
        uses: actions/checkout@v2
      - name: установка питона
        uses: actions/setup-python@v5
        with:
          python-version: 3.12
      - name: installing requirements
        run: pip install -r requirements.txt
      - name: Linter
        run: flake8 django_ORM1 --exclude migrations --ignore E501,F401,E302,W293,W391,W292
      - name: tests
        run: python django_ORM1/manage.py test





